<h1 style="text-align: center;">NATHAN JOSH CACHO - PA #2</h1>

# Normalization Problem

In [1]:
import numpy as np

In [5]:
x = np.random.rand(5,5)
x_mean = mean = x.mean()
x_std = x.std()
z = (x - x_mean)/x_std

np.save("x_normalized.npy",z)

print("Normalized 5x5 array saved as X_normalized.npy")
print(z)

Normalized 5x5 array saved as X_normalized.npy
[[ 0.01205117  0.30059692 -0.53222337  0.27768585  0.14647388]
 [-0.50642768  0.62792237 -1.65837186  0.06351937  1.25981967]
 [-0.25328151 -1.96669214 -0.15493423 -1.5730305   1.17411716]
 [ 0.58845525  0.91303565  0.96224187 -0.72155056  1.11897323]
 [-1.10103274  1.44271811  1.48514568 -0.43603733 -1.46917427]]


# Divisible by 3 Problem

In [6]:
A = np.arange(1, 101) ** 2
A = A.reshape(10,10)

div = A[A % 3 == 0]
np.save("div.npy", div)

print("\n10x10 array of squares:")
print(A)
print("\nElements divisible by 3 saved as div.npy")
print(div)


10x10 array of squares:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3 saved as div.npy
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
